# Generated by Django 6.1.1 on 2026-10-01 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Llavero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_activacion', models.CharField(blank=True, max_length=254, unique=True)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('VINCULADO', 'Vinculado'), ('EXPIRO', 'Expiró')], default='NUEVO', max_length=100)),
                ('identificador_publico', models.CharField(blank=True, max_length=254, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llaveros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Llavero',
                'verbose_name_plural': 'Llaveros',
            },
        ),
        migrations.CreateModel(
            name='Escaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(max_length=254)),
                ('llavero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llaveros', to='llaveros.llavero')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, max_length=254, upload_to='')),
                ('sePerdio', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='llavero',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llaveros', to='llaveros.mascota'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=254)),
                ('facebook', models.CharField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=14)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='llaveros.perfil')),
            ],
        ),
    ]
