# Generated by Django 6.1.1 on 2026-09-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llaveros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='estado',
        ),
        migrations.AddField(
            model_name='mascota',
            name='sePerdio',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Vacuna',
        ),
    ]
