# Generated by Django 6.1.1 on 2026-10-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llaveros', '0002_remove_perfil_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llavero',
            name='mascota',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llavero', to='llaveros.mascota'),
        ),
    ]
