# Generated by Django 6.1.1 on 2026-09-23 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llaveros', '0003_alter_direccion_usuario_alter_mascota_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llavero',
            name='mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llaveros', to='llaveros.mascota'),
        ),
    ]
