# Generated by Django 6.1.1 on 2026-10-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llaveros', '0003_alter_llavero_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='usuario',
        ),
    ]
