# Generated by Django 6.1.1 on 2026-09-23 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llaveros', '0004_alter_llavero_mascota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llavero',
            options={'verbose_name': 'Llavero', 'verbose_name_plural': 'Llaveros'},
        ),
        migrations.AddField(
            model_name='llavero',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='llavero',
            name='codigo_activacion',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='llavero',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('VINCULADO', 'Vinculado'), ('EXPIRO', 'Expiró'), ('DESVINCULADO', 'Desvinculado')], default='NUEVO', max_length=100),
        ),
        migrations.AlterField(
            model_name='llavero',
            name='identificador_publico',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='llavero',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llaveros', to='llaveros.mascota'),
        ),
    ]
