# Generated by Django 6.1.1 on 2026-09-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llaveros', '0005_alter_llavero_options_llavero_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llavero',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('VINCULADO', 'Vinculado'), ('EXPIRO', 'Expiró'), ('DESVINCULADO', 'Desvinculado'), ('SIN_MASCOTA', 'Sin mascota')], default='NUEVO', max_length=100),
        ),
        migrations.AlterField(
            model_name='llavero',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llaveros', to='llaveros.mascota'),
        ),
    ]
