# Generated by Django 6.1.1 on 2026-09-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llaveros', '0006_alter_llavero_estado_alter_llavero_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llavero',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('VINCULADO', 'Vinculado'), ('EXPIRO', 'Expiró'), ('SIN_MASCOTA', 'Sin mascota')], default='NUEVO', max_length=100),
        ),
    ]
