# Generated by Django 6.1.1 on 2026-09-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llaveros', '0007_alter_llavero_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llavero',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('VINCULADO', 'Vinculado'), ('EXPIRO', 'Expiró')], default='NUEVO', max_length=100),
        ),
    ]
